### ISSUE TITLE
ant compiling failure

### ISSUE THREAD

**Issue by risseraka** [tinymce/js-build-tools#1]
On freshly untared moxiecode-js-build-tools-49783e0.tar.gz, building with ant fails.
Error code at the end of the issue.

It was fixed by using FileInputStream instead of BufferedReader in ValidElementsParser.java.

//BufferedReader in = new BufferedReader(new FileReader(propFile));
parseProperties.load(new FileInputStream(propFile));
//in.close();

---

Buildfile: build.xml

build:
    [mkdir] Created dir: /../../moxiecode-js-build-tools-49783e0/tmp/classes
    [javac] Compiling 16 source files to /../../moxiecode-js-build-tools-49783e0/tmp/classes
    [javac] /../../moxiecode-js-build-tools-49783e0/src/com/moxiecode/dtd2js/ValidElementsParser.java:299: load(java.io.InputStream) in java.util.Properties cannot be applied to (java.io.BufferedReader)
    [javac]                     parseProperties.load(in);
    [javac]                                        ^
    [javac] 1 error

BUILD FAILED
/../../moxiecode-js-build-tools-49783e0/build.xml:45: Compile failed; see the compiler error output for details.

Total time: 2 seconds

**Comment by tomap** [comment]
Using last ant and  last JDK and last tared sources on windows XP, it worked for me
